name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    # Обновленный шаг для запуска исполняемого файла 'G26Projects'
    - name: Run G26Projects Executable
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ./G26Project # Убедитесь, что здесь указан правильный путь к исполняемому файлу 'G26Projects'

    # Обновленный шаг для запуска тестов 'G26Tests'
    - name: Run G26Tests
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ./G26Tests # Убедитесь, что здесь указан правильный путь к исполняемому файлу тестов 'G26Tests'

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: ${{runner.workspace}}/build
